spring:
  application:
    name: devops-member
  jpa:
    generate-ddl: true
    show-sql: true # 打印SQL语句
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # create每次运行都删除原有表创建新表,update不用每次创建新表
server:
  port: 8081
# servlet:
  ##    context-path: /member #业务接口上下文路径
management:
  server:
    port: 18081 #管理端口,避免管理接口被外部通过业务端口调用
#    servlet:
#      context-path: /management #管理接口上下文路径，如果业务端口和管理端口相同时不生效
  endpoints:
    web:
      base-path: / #管理路径，默认/actuator
  endpoint:
    health:
      show-details: always #显示健康检查详细信息，如果状态为DOWN可以很快定位问题
