spring:
  application:
    name: devops-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devops-member?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  flyway:
      # 启用或禁用 flyway
      enabled: true
      # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
      clean-disabled: true
      # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
      locations: classpath:db/flyway
      #  metadata 版本控制信息表 默认 flyway_schema_history
      table: flyway_schema_history
      # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
      # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
      baseline-on-migrate: true
      # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
      baseline-version: 1
      # 字符编码 默认 UTF-8
      encoding: UTF-8
      # 是否允许不按顺序迁移 开发建议 true  生产建议 false
      out-of-order: false
      # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
      validate-on-migrate: true
server:
  port: 8081
# servlet:
  ##    context-path: /member #业务接口上下文路径
management:
  server:
    port: 18081 #管理端口,避免管理接口被外部通过业务端口调用
#    servlet:
#      context-path: /management #管理接口上下文路径，如果业务端口和管理端口相同时不生效
  endpoints:
    web:
      base-path: / #管理路径，默认/actuator
  endpoint:
    health:
      show-details: always #显示健康检查详细信息，如果状态为DOWN可以很快定位问题
