spring:
  application:
    name: member
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081

management:
  endpoints:
    web:
      base-path: / #管理路径
  endpoint:
    health:
      show-details: always #显示健康检查详细信息，如果状态为DOWN可以很快定位问题
  server:
    port: 18081 #管理端口