server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      ################################
      # 配置允许跨域请求
      ################################
      filter:
        remove-hop-by-hop:
          headers:
            # 以下是去掉网关默认去掉的请求响应头
            - trailer
            - te
            - keep-alive
            - transfer-encoding
            - upgrade
            - proxy-authenticate
            - connection
            - proxy-authorization
            - x-application-context
            # 以下是去掉服务层面定义的跨域
            - access-control-allow-credentials
            - access-control-allow-headers
            - access-control-allow-methods
            - access-control-allow-origin
            - access-control-max-age
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 3628800
      default-filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: default
            fallbackUri: forward:/defaultfallback
      routes:
        - id: member
          uri: http://localhost:8081
          predicates:
            - Path=/member/**
        - id: cmdb
          uri: http://localhost:8082
          predicates:
            - Path=/cmdb/**

# hystrix 信号量隔离，5秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

auth:
  white:
    urls:
      - /member/auth/login
