server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: member
          uri: http://localhost:8081
          predicates:
            - Path=/member/**